#ifndef NATIVEFINSTALLER_MAIN_H
#define NATIVEFINSTALLER_MAIN_H

static const char* g_json = "{\n"
						  "  \"inheritsFrom\": \"${mcVersion}\",\n"
						  "  \"id\": \"fabric-${loaderVersion}-${mcVersion}\",\n"
						  "  \"time\": \"2020-10-29T09:17:25+05:30\",\n"
						  "  \"releaseTime\": \"2020-10-29T09:17:25+05:30\",\n"
						  "  \"type\": \"release\",\n"
						  "  \"libraries\": [\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:tiny-mappings-parser:0.2.2.14\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:sponge-mixin:0.8.2+build.24\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:tiny-remapper:0.3.0.70\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:fabric-loader-sat4j:2.3.5.4\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"com.google.jimfs:jimfs:1.2-fabric\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"org.ow2.asm:asm:9.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"org.ow2.asm:asm-analysis:9.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"org.ow2.asm:asm-commons:9.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"org.ow2.asm:asm-tree:9.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"org.ow2.asm:asm-util:9.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"com.google.guava:guava:21.0\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:intermediary:${mcVersion}\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    },\n"
						  "    {\n"
						  "      \"name\": \"net.fabricmc:fabric-loader:${loaderVersion}\",\n"
						  "      \"url\": \"https://maven.fabricmc.net/\"\n"
						  "    }\n"
						  "  ],\n"
						  "  \"mainClass\": \"net.fabricmc.loader.launch.knot.KnotClient\",\n"
						  "  \"minimumLauncherVersion\": 0,\n"
						  "  \"downloads\": {},\n"
						  "  \"arguments\": {\n"
						  "    \"game\": []\n"
						  "  }\n"
						  "}";

int main(int argc, char **argv);

#endif
